# syntax=docker/dockerfile:1.7

FROM node:24-alpine AS builder
WORKDIR /app

COPY package.json package-lock.json .npmrc ./
RUN --mount=type=secret,id=npm_token \
    --mount=type=cache,target=/root/.npm \
    NODE_AUTH_TOKEN="$(cat /run/secrets/npm_token)" npm ci --no-audit --no-fund

# Declared after `npm ci`: a changed build arg invalidates every RUN below it,
# and CI passes a new VITE_COMMIT on every build.
# The service URLs default to the same-origin paths the reverse proxy serves.
ARG VITE_REGISTRY_URL=/registry
ARG VITE_RELAYER_URL=/relayer
ARG VITE_FMD_URL=/fmd
ARG VITE_METAQUOTER_URL=/metaquoter

ARG VITE_COMMIT

ENV VITE_REGISTRY_URL=$VITE_REGISTRY_URL \
    VITE_RELAYER_URL=$VITE_RELAYER_URL \
    VITE_FMD_URL=$VITE_FMD_URL \
    VITE_METAQUOTER_URL=$VITE_METAQUOTER_URL \
    VITE_COMMIT=$VITE_COMMIT

COPY . .
# Maps are deleted in this stage: a delete in the runtime stage would leave
# them extractable from the COPY layer beneath it.
RUN npm run build && find dist -name '*.map' -delete

FROM nginx:1.30-alpine AS runtime
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY security-headers.conf /etc/nginx/security-headers.conf
# Generated by `npm run build` (`linkHeaders` in vite/plugins/link-headers.ts).
# Kept outside dist/ because everything under dist/ is served.
COPY --from=builder /app/.nginx/link-headers.conf /etc/nginx/link-headers.conf
COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
