# syntax=docker/dockerfile:1.7

FROM node:24-alpine AS builder
WORKDIR /app

COPY package.json package-lock.json .npmrc ./
RUN --mount=type=secret,id=npm_token \
    --mount=type=cache,target=/root/.npm \
    NODE_AUTH_TOKEN="$(cat /run/secrets/npm_token)" npm ci --no-audit --no-fund

# Declared after `npm ci` on purpose: a changed build arg invalidates every RUN
# below it, and CI passes a new VITE_COMMIT on every build, so declaring these
# first would reinstall dependencies each time.
#
# The service URLs default to the same-origin paths the deployment's reverse
# proxy serves (and `.env.example` uses); pass a build arg to point elsewhere.
ARG VITE_REGISTRY_URL=/registry
ARG VITE_RELAYER_URL=/relayer
ARG VITE_FMD_URL=/fmd
ARG VITE_METAQUOTER_URL=/metaquoter

ARG VITE_COMMIT

ENV VITE_REGISTRY_URL=$VITE_REGISTRY_URL \
    VITE_RELAYER_URL=$VITE_RELAYER_URL \
    VITE_FMD_URL=$VITE_FMD_URL \
    VITE_METAQUOTER_URL=$VITE_METAQUOTER_URL \
    VITE_COMMIT=$VITE_COMMIT

COPY . .
# Maps are deleted here, not in the runtime stage: a delete in a later layer
# hides the files but leaves them in the COPY layer beneath it, where anyone
# who pulls the image can still extract them.
RUN npm run build && find dist -name '*.map' -delete

FROM nginx:1.30-alpine AS runtime
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY security-headers.conf /etc/nginx/security-headers.conf
# Generated by `npm run build`, not committed — see `linkHeaders` in
# vite/plugins/link-headers.ts. Lives outside dist/ on purpose: everything under dist/ is
# served, and this is nginx configuration.
COPY --from=builder /app/.nginx/link-headers.conf /etc/nginx/link-headers.conf
COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
